require("dotenv").config();

const Config = {
  PORT: process.env.PORT || 3000,
  DATABASE_URL: process.env.DATABASE_URL,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY || "Secret",
  JWT_SECRET_KEY_TEMP: process.env.JWT_SECRET_KEY_TEMP,
  SUPERADMIN_DEFAULT_PASSWORD: process.env.SUPERADMIN_DEFAULT_PASSWORD || "strongkey",
  SUPERADMIN_PHONE: process.env.SUPERADMIN_PHONE || "",
  SUPERADMIN_EMAIL: process.env.SUPERADMIN_EMAIL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_LATEST_REDIRECT_URL: process.env.GOOGLE_LATEST_REDIRECT_URL,
  GOOGLE_REDIRECT_URI_FOR_CONNECT: process.env.GOOGLE_REDIRECT_URI_FOR_CONNECT,
  ESKIZ_LOGIN: process.env.ESKIZ_LOGIN,
  ESKIZ_PASSWORD: process.env.ESKIZ_PASSWORD,
  ESKIZ_FROM: process.env.ESKIZ_FROM,
  BOT_API: process.env.BOT_API,
  ISSUER: process.env.ISSUER,
  AUDIENCE: process.env.AUDIENCE,
  CRYPTO_SECRET_KEY: process.env.CRYPTO_SECRET_KEY || "CrYpTo_SeCrEt_K3Y!",
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  ORIGIN: process.env.ORIGIN || "*",

  LOGIN_OTP_TTL_PERIOD_1: 1000 * 60 * 4,
  LOGIN_OTP_TTL_PERIOD_2: 1000 * 60 * 8,
  LOGIN_OTP_TTL_PERIOD_3: 1000 * 60 * 30,
  LOGIN_OTP_TTL_PERIOD_4: 1000 * 60 * 60 * 6,
  // LOGIN_OTP_TTL_PERIOD_1: 1000,
  // LOGIN_OTP_TTL_PERIOD_2: 1000,
  // LOGIN_OTP_TTL_PERIOD_3: 1000,
  // LOGIN_OTP_TTL_PERIOD_4: 1000,

  DEV_BOT_API: process.env.DEV_BOT_API,
  DEV_CHAT_ID: process.env.DEV_CHAT_ID,
  DB_BACKUP_CHAT_ID: process.env.DB_BACKUP_CHAT_ID,
  CALLMASTER_KEY: process.env.CALLMASTER_KEY,

  S3_KEY: process.env.S3_KEY,
  S3_SECRET: process.env.S3_SECRET,
  S3_REGION: process.env.S3_REGION,
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_BUCKET: process.env.S3_BUCKET,
};

module.exports = Config;
